export default [
  {name: "country", value: "Andorra"},
  {name: "country", value: "United Arab Emirates"},
  {name: "country", value: "Afghanistan"},
  {name: "country", value: "Antigua and Barbuda"},
  {name: "country", value: "Anguilla"},
  {name: "country", value: "Albania"},
  {name: "country", value: "Armenia"},
  {name: "country", value: "Angola"},
  {name: "country", value: "Antarctica"},
  {name: "country", value: "Argentina"},
  {name: "country", value: "American Samoa"},
  {name: "country", value: "Austria"},
  {name: "country", value: "Australia"},
  {name: "country", value: "Aruba"},
  {name: "country", value: "Azerbaijan"},
  {name: "country", value: "Bosnia and Herzegovina"},
  {name: "country", value: "Barbados"},
  {name: "country", value: "Bangladesh"},
  {name: "country", value: "Belgium"},
  {name: "country", value: "Burkina Faso"},
  {name: "country", value: "Bulgaria"},
  {name: "country", value: "Bahrain"},
  {name: "country", value: "Burundi"},
  {name: "country", value: "Benin"},
  {name: "country", value: "Saint Barthelemy"},
  {name: "country", value: "Bermuda"},
  {name: "country", value: "Brunei"},
  {name: "country", value: "Bolivia"},
  {name: "country", value: "Caribbean Netherlands"},
  {name: "country", value: "Brazil"},
  {name: "country", value: "Bahamas"},
  {name: "country", value: "Bhutan"},
  {name: "country", value: "Botswana"},
  {name: "country", value: "Belarus"},
  {name: "country", value: "Belize"},
  {name: "country", value: "Canada"},
  {name: "country", value: "Cocos (Keeling)vIslands"},
  {name: "country", value: "Congo (Kinshasa)"},
  {name: "country", value: "Central AfricanvRepublic"},
  {name: "country", value: "Congo (Brazzaville)"},
  {name: "country", value: "Switzerland"},
  {name: "country", value: "Cote d'Ivoire"},
  {name: "country", value: "Cook Islands"},
  {name: "country", value: "Chile"},
  {name: "country", value: "Cameroon"},
  {name: "country", value: "China"},
  {name: "country", value: "Colombia"},
  {name: "country", value: "CostaRica"},
  {name: "country", value: "Cuba"},
  {name: "country", value: "CapeVerde"},
  {name: "country", value: "Curacao"},
  {name: "country", value: "Christmas Island"},
  {name: "country", value: "Cyprus"},
  {name: "country", value: "Czechia"},
  {name: "country", value: "Germany"},
  {name: "country", value: "Djibouti"},
  {name: "country", value: "Denmark"},
  {name: "country", value: "Dominica"},
  {name: "country", value: "Dominican Republic"},
  {name: "country", value: "Algeria"},
  {name: "country", value: "Ecuador"},
  {name: "country", value: "Estonia"},
  {name: "country", value: "Egypt"},
  {name: "country", value: "Western Sahara"},
  {name: "country", value: "Eritrea"},
  {name: "country", value: "Spain"},
  {name: "country", value: "Ethiopia"},
  {name: "country", value: "Finland"},
  {name: "country", value: "Fiji"},
  {name: "country", value: "Falkland Islands"},
  {name: "country", value: "Micronesia"},
  {name: "country", value: "Faroe Islands"},
  {name: "country", value: "France"},
  {name: "country", value: "Gabon"},
  {name: "country", value: "United Kingdomreunion country"},
  {name: "country", value: "Grenada"},
  {name: "country", value: "Georgia"},
  {name: "country", value: "French Guiana"},
  {name: "country", value: "Guernsey"},
  {name: "country", value: "Ghana"},
  {name: "country", value: "Gibraltar"},
  {name: "country", value: "Greenland"},
  {name: "country", value: "Gambia"},
  {name: "country", value: "Guinea"},
  {name: "country", value: "Guadeloupe"},
  {name: "country", value: "EquatorialGuinea"},
  {name: "country", value: "Greece"},
  {name: "country", value: "South Georgia and the South Sandwich Islands"},
  {name: "country", value: "Guatemala"},
  {name: "country", value: "Guam"},
  {name: "country", value: "Guinea-Bissau"},
  {name: "country", value: "Guyana"},
  {name: "country", value: "HongKong"},
  {name: "country", value: "Honduras"},
  {name: "country", value: "Croatia"},
  {name: "country", value: "Haiti"},
  {name: "country", value: "Hungary"},
  {name: "country", value: "Indonesia"},
  {name: "country", value: "Ireland"},
  {name: "country", value: "Israel"},
  {name: "country", value: "Isle of Man"},
  {name: "country", value: "India"},
  {name: "country", value: "British Indian Ocean Territory"},
  {name: "country", value: "Iraq"},
  {name: "country", value: "Iran"},
  {name: "country", value: "Iceland"},
  {name: "country", value: "Italy"},
  {name: "country", value: "Jersey"},
  {name: "country", value: "Jamaica"},
  {name: "country", value: "Jordan"},
  {name: "country", value: "Japan"},
  {name: "country", value: "Kenya"},
  {name: "country", value: "Kyrgyzstan"},
  {name: "country", value: "Cambodia"},
  {name: "country", value: "Kiribati"},
  {name: "country", value: "Comoros"},
  {name: "country", value: "Saint Kitts and Nevis"},
  {name: "country", value: "North Korea"},
  {name: "country", value: "South Korea"},
  {name: "country", value: "Kuwait"},
  {name: "country", value: "Cayman Islands"},
  {name: "country", value: "Kazakhstan"},
  {name: "country", value: "Laos"},
  {name: "country", value: "Lebanon"},
  {name: "country", value: "Saint Lucia"},
  {name: "country", value: "Liechtenstein"},
  {name: "country", value: "Sri Lanka"},
  {name: "country", value: "Liberia"},
  {name: "country", value: "Lesotho"},
  {name: "country", value: "Lithuania"},
  {name: "country", value: "Luxembourg"},
  {name: "country", value: "Latvia"},
  {name: "country", value: "Libya"},
  {name: "country", value: "Morocco"},
  {name: "country", value: "Monaco"},
  {name: "country", value: "Moldova"},
  {name: "country", value: "Montenegro"},
  {name: "country", value: "Saint Martin"},
  {name: "country", value: "Madagascar"},
  {name: "country", value: "Marshall Islands"},
  {name: "country", value: "Macedonia"},
  {name: "country", value: "Mali"},
  {name: "country", value: "Burma"},
  {name: "country", value: "Mongolia"},
  {name: "country", value: "Macau"},
  {name: "country", value: "Northern Mariana Islands"},
  {name: "country", value: "Martinique"},
  {name: "country", value: "Mauritania"},
  {name: "country", value: "Montserrat"},
  {name: "country", value: "Malta"},
  {name: "country", value: "Mauritius"},
  {name: "country", value: "Maldives"},
  {name: "country", value: "Malawi"},
  {name: "country", value: "Mexico"},
  {name: "country", value: "Malaysia"},
  {name: "country", value: "Mozambique"},
  {name: "country", value: "Namibia"},
  {name: "country", value: "New Caledonia"},
  {name: "country", value: "Niger"},
  {name: "country", value: "Norfolk Island"},
  {name: "country", value: "Nigeria"},
  {name: "country", value: "Nicaragua"},
  {name: "country", value: "Netherlands"},
  {name: "country", value: "Norway"},
  {name: "country", value: "Nepal"},
  {name: "country", value: "Nauru"},
  {name: "country", value: "Niue"},
  {name: "country", value: "New Zealand"},
  {name: "country", value: "Oman"},
  {name: "country", value: "Panama"},
  {name: "country", value: "Peru"},
  {name: "country", value: "FrenchPolynesia"},
  {name: "country", value: "Papua New Guinea"},
  {name: "country", value: "Philippines"},
  {name: "country", value: "Pakistan"},
  {name: "country", value: "Poland"},
  {name: "country", value: "Saint Pierre and Miquelon"},
  {name: "country", value: "Pitcairn"},
  {name: "country", value: "Puerto Rico"},
  {name: "country", value: "Palestinian Territory"},
  {name: "country", value: "Portugal"},
  {name: "country", value: "Palau"},
  {name: "country", value: "Paraguay"},
  {name: "country", value: "Qatar"},
  {name: "country", value: "Reunion"},
  {name: "country", value: "Romania"},
  {name: "country", value: "Serbia"},
  {name: "country", value: "Russia"},
  {name: "country", value: "Rwanda"},
  {name: "country", value: "Saudi Arabia"},
  {name: "country", value: "Solomon Islands"},
  {name: "country", value: "Seychelles"},
  {name: "country", value: "Sudan"},
  {name: "country", value: "Sweden"},
  {name: "country", value: "Singapore"},
  {name: "country", value: "Saint Helena"},
  {name: "country", value: "Slovenia"},
  {name: "country", value: "Slovakia"},
  {name: "country", value: "Sierra Leone"},
  {name: "country", value: "San Marino"},
  {name: "country", value: "Senegal"},
  {name: "country", value: "Somalia"},
  {name: "country", value: "Suriname"},
  {name: "country", value: "South Sudan"},
  {name: "country", value: "Sao Tome and Principe"},
  {name: "country", value: "El Salvador"},
  {name: "country", value: "Sint Maarten"},
  {name: "country", value: "Syria"},
  {name: "country", value: "Swaziland"},
  {name: "country", value: "Turks and Caicos Islands"},
  {name: "country", value: "Chad"},
  {name: "country", value: "French Southern Territories"},
  {name: "country", value: "Togo"},
  {name: "country", value: "Thailand"},
  {name: "country", value: "Tajikistan"},
  {name: "country", value: "Tokelau"},
  {name: "country", value: "Timor-Leste"},
  {name: "country", value: "Turkmenistan"},
  {name: "country", value: "Tunisia"},
  {name: "country", value: "Tonga"},
  {name: "country", value: "Turkey"},
  {name: "country", value: "Trinidad and Tobago"},
  {name: "country", value: "Tuvalu"},
  {name: "country", value: "Taiwan"},
  {name: "country", value: "Tanzania"},
  {name: "country", value: "Ukraine"},
  {name: "country", value: "Uganda"},
  {name: "country", value: "United States Minor Outlying Islands"},
  {name: "country", value: "United States"},
  {name: "country", value: "Uruguay"},
  {name: "country", value: "Uzbekistan"},
  {name: "country", value: "Vatican City"},
  {name: "country", value: "Saint Vincent and the Grenadines"},
  {name: "country", value: "Venezuela"},
  {name: "country", value: "British Virgin Islands"},
  {name: "country", value: "U.S.Virgin Islands"},
  {name: "country", value: "Vietnam"},
  {name: "country", value: "Vanuatu"},
  {name: "country", value: "Wallis and Futuna"},
  {name: "country", value: "Samoa"},
  {name: "country", value: "Kosovo"},
  {name: "country", value: "Yemen"},
  {name: "country", value: "Mayotte"},
  {name: "country", value: "South Africa"},
  {name: "country", value: "Zambia"},
  {name: "country", value: "Zimbabwe"},
  {name: "type", value: "airport"},
  {name: "type", value: "balloonport"},
  {name: "type", value: "heliport"},
  {name: "type", value: "closed"}
];